server {
  listen 80;
  listen [::]:80;
  gzip on;
  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri /index.html;
  }

  access_log /dev/stdout;
  error_log /dev/stderr info;
}